spring:
  application:
    name: client

server:
  port: 8081

app:
  server-scheme: "http"
  server-host: "127.0.0.1"
  server-port: "8080"
  server-websocket-client-name-query-param-name: "name"
  server-websocket-destination: "/ws"
  server-send-message-destination: "/api/chat"
  server-subscription-destination: "/user/queue/messages"
  client-name: "1"
